# Generated by Django 4.2.16 on 2025-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_since', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='straymapper/report-photos')),
                ('geometry', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
